#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hour=0

while [ "$hour" -lt 13 ]; do
	minutes=1
	echo "Hour: $hour"

	while [ "$minutes" -lt 60 ]; do
		echo "$minutes"
		((minutes++))
	done
	((hour++))
done
