#!/usr/bin/env bash
# Bash script that displays the content of the current directory
# In a list format, where only the part of the name after the first dash is displayed

for file in *; do
	if [[ "$file" != .* ]]; then
		name=$(echo "$file" | cut -d'-' -f2-)

		echo "$name"
	fi
done
